//ERROR
export const ERROR_CREATE_COMMENT = 'ERROR_CREATE_COMMENT';
export const ERROR_DELETE_COMMENT = 'ERROR_DELETE_COMMENT';
export const ERROR_NOW_ALLOW_TO_REPLY_COMMENT_LEVEL_3 = 'ERROR_NOW_ALLOW_TO_REPLY_COMMENT_LEVEL_3';
export const ERROR_REACT_COMMENT = 'ERROR_REACT_COMMENT';

//SUCCESS
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const REACT_COMMENT_SUCCESS = 'REACT_COMMENT_SUCCESS';
