//Error
export const ERROR_CREATE_CONVERSATION = 'ERROR_CREATE_CONVERSATION';
export const ERROR_EXISTED_CONVERSATION = 'ERROR_EXISTED_CONVERSATION';
export const ERROR_FIND_CONVERSATION_BY_ID = 'ERROR_FIND_CONVERSATION_BY_ID';
export const ERROR_NOT_FOUND_CONVERSATION = 'ERROR_NOT_FOUND_CONVERSATION';
export const ERROR_ADD_MESSAGE_TO_CONVERSATION = 'ERROR_ADD_MESSAGE_TO_CONVERSATION';
export const ERROR_USER_NOT_IN_CONVERSATION = 'ERROR_USER_NOT_IN_CONVERSATION';
export const ERROR_GET_CONVERSATIONS = 'ERROR_GET_CONVERSATIONS';
export const ERROR_FIND_ONE_CONVERSATION = 'ERROR_FIND_ONE_CONVERSATION';
export const ERROR_RENAME_CONVERSATION = 'ERROR_RENAME_CONVERSATION';
export const ERROR_NEW_AMIN_NOT_IN_CONVERSATION = 'ERROR_NEW_AMIN_NOT_IN_CONVERSATION';
export const ERROR_SWITCH_ADMIN = 'ERROR_SWITCH_ADMIN';
export const ERROR_NOT_IS_CONV_ADMIN = 'ERROR_NOT_IS_CONV_ADMIN';
export const ERROR_USER_NOT_IN_CONV = 'ERROR_USER_NOT_IN_CONV';
export const ERROR_CANNOT_REMOVE_MYSEFF = 'ERROR_CANNOT_REMOVE_MYSEFF';

//Success
export const CREATE_CONVERSATION_SUCCESSFULLY = 'CREATE_CONVERSATION_SUCCESSFULLY';
export const GET_CONVERSATIONS_SUCCESSFULLY = 'GET_CONVERSATIONS_SUCCESSFULLY';
export const REMOVE_MEMBER_SUCCESSFULLY = 'REMOVE_MEMBER_SUCCESSFULLY';
export const RENAME_CONVERSATION_SUCCESSFULLY = 'RENAME_CONVERSATION_SUCCESSFULLY';
export const SWITCH_ADMIN_SUCCESSFULLY = 'SWITCH_ADMIN_SUCCESSFULLY';
