//Error
export const ERROR_CREATE_CONVERSATION = 'ERROR_CREATE_CONVERSATION';
export const ERROR_EXISTED_CONVERSATION = 'ERROR_EXISTED_CONVERSATION';
export const ERROR_FIND_CONVERSATION_BY_ID = 'ERROR_FIND_CONVERSATION_BY_ID';
export const ERROR_NOT_FOUND_CONVERSATION = 'ERROR_NOT_FOUND_CONVERSATION';
export const ERROR_ADD_MESSAGE_TO_CONVERSATION = 'ERROR_ADD_MESSAGE_TO_CONVERSATION';
export const ERROR_USER_NOT_IN_CONVERSATION = 'ERROR_USER_NOT_IN_CONVERSATION';
export const ERROR_GET_CONVERSATIONS = 'ERROR_GET_CONVERSATIONS';

//Success
export const CREATE_CONVERSATION_SUCCESSFULLY = 'CREATE_CONVERSATION_SUCCESSFULLY';
export const GET_CONVERSATIONS_SUCCESSFULLY = 'GET_CONVERSATIONS_SUCCESSFULLY';
