// Success
export const CREATE_EDUCATION_SUCCESS = 'CREATE_EDUCATION_SUCCESS';
export const GET_EDUCATIONS_SUCCESS = 'GET_EDUCATIONS_SUCCESS';

// Error
export const ERROR_CREATE_EDUCATION = 'ERROR_CREATE_EDUCATION';
export const ERROR_GET_EDUCATIONS = 'ERROR_GET_EDUCATIONS';
