//ERROR
export const ERROR_CREATE_FRIEND_REQ = 'ERROR_CREATE_FRIEND_REQ';
export const ERROR_FRIEND_REQ_EXISTED = 'ERROR_FRIEND_REQ_EXISTED';
export const ERROR_CHECK_RELATIONSHIP = 'ERROR_CHECK_RELATIONSHIP';

//SUCCESS
export const CREATE_FRIEND_REQ_SUCCESS = 'CREATE_FRIEND_REQ_SUCCESS';
export const CHECK_RELATIONSHIP_SUCCESS = 'CHECK_RELATIONSHIP_SUCCESS';
