//ERROR
export const ERROR_CREATE_FRIEND_REQ = 'ERROR_CREATE_FRIEND_REQ';
export const ERROR_FRIEND_REQ_EXISTED = 'ERROR_FRIEND_REQ_EXISTED';
export const ERROR_CHECK_RELATIONSHIP = 'ERROR_CHECK_RELATIONSHIP';
export const ERROR_GET_RECEIVE_FRIEND_REQ_FOR_PAGINATION = 'ERROR_GET_RECEIVE_FRIEND_REQ_FOR_PAGINATION';
export const ERROR_GET_RECEIVE_FRIEND_REQ_PAGINATION = 'ERROR_GET_RECEIVE_FRIEND_REQ_PAGINATION';
export const ERROR_ACCEPT_FRIEND_REQ = 'ERROR_ACCEPT_FRIEND_REQ';
export const ERROR_DELETE_FRIEND_REQ = 'ERROR_DELETE_FRIEND_REQ';
export const ERROR_FIND_USER_BY_NAME = 'ERROR_FIND_USER_BY_NAME';

//SUCCESS
export const CREATE_FRIEND_REQ_SUCCESS = 'CREATE_FRIEND_REQ_SUCCESS';
export const CHECK_RELATIONSHIP_SUCCESS = 'CHECK_RELATIONSHIP_SUCCESS';
export const GET_FRIEND_REQ_FOR_PAGINATION_SUCCESS = 'GET_FRIEND_REQ_FOR_PAGINATION_SUCCESS';
export const GET_FRIEND_REQ_PAGINATION_SUCCESS = 'GET_FRIEND_REQ_PAGINATION_SUCCESS';
export const DELETE_FRIEND_REQ_SUCCESS = 'DELETE_FRIEND_REQ_SUCCESS';
export const FIND_USER_BY_NAME_SUCCESS = 'FIND_USER_BY_NAME_SUCCESS';
