//Error
export const ERROR_CREATE_MESSAGE = 'ERROR_CREATE_MESSAGE';
export const ERROR_GET_PAGINATE_MESSAGES = 'ERROR_GET_PAGINATE_MESSAGES';
export const ERROR_AFTER_NOT_FOUND = 'ERROR_AFTER_NOT_FOUND';

//Sucess
export const CREATE_MESSAGE_SUCCESSFULLY = 'CREATE_MESSAGE_SUCCESSFULLY';
export const GET_MESSAGES_SUCCESSFULLY = 'GET_MESSAGES_SUCCESSFULLY';
