//Error
export const ERROR_CREATE_MESSAGE = 'ERROR_CREATE_MESSAGE';
export const ERROR_GET_PAGINATE_MESSAGES = 'ERROR_GET_PAGINATE_MESSAGES';
export const ERROR_AFTER_NOT_FOUND = 'ERROR_AFTER_NOT_FOUND';
export const ERROR_SEEN_MESSAGE = 'ERROR_SEEN_MESSAGE';
export const ERROR_MESSAGE_NOT_FOUND = 'ERROR_MESSAGE_NOT_FOUND';
export const ERROR_USER_NOT_ALLOWED_TO_SEE_MESSAGE = 'ERROR_USER_NOT_ALLOWED_TO_SEE_MESSAGE';
export const ERROR_CREATE_SYSTEM_MESSAGE = 'ERROR_CREATE_SYSTEM_MESSAGE';
export const ERROR_DELETE_MESSAGE = 'ERROR_DELETE_MESSAGE';

//Sucess
export const CREATE_MESSAGE_SUCCESSFULLY = 'CREATE_MESSAGE_SUCCESSFULLY';
export const GET_MESSAGES_SUCCESSFULLY = 'GET_MESSAGES_SUCCESSFULLY';
export const SEEN_MESSAGE_SUCCESSFULLY = 'SEEN_MESSAGE_SUCCESSFULLY';
