//ERROR
export const ERROR_CREATE_NOTI = 'ERROR_CREATE_NOTI';
export const ERROR_GET_NOTIFY_FOR_PAGINATION = 'ERROR_GET_NOTIFY_FOR_PAGINATION';
export const ERROR_GET_NOTIFY_PAGINATION = 'ERROR_GET_NOTIFY_PAGINATION';
export const ERROR_HANDLE_SEE_NOTIFY = 'ERROR_HANDLE_SEE_NOTIFY';

//SUCCESS
export const CREATE_NOTI_SUCCESS = 'CREATE_NOTI_SUCCESS';
export const GET_NOTIFY_FOR_PAGINATION_SUCCESS = 'GET_NOTIFY_FOR_PAGINATION_SUCCESS';
export const GET_NOTIFY_PAGINATION_SUCCESS = 'GET_NOTIFY_PAGINATION_SUCCESS';
export const HANDLE_SEE_NOTIFY_SUCCESS = 'HANDLE_SEE_NOTIFY_SUCCESS';
