//ERROR
export const ERROR_CREATE_FEELING = 'ERROR_CREATE_FEELING';
export const ERROR_FEELING_IS_EXISTED = 'ERROR_FEELING_IS_EXISTED';
export const ERROR_UPDATE_FEELING = 'ERROR_UPDATE_FEELING';
export const ERROR_FIND_ALL_FEELING = 'ERROR_FIND_ALL_FEELING';
export const ERROR_DELETE_FEELING = 'ERROR_DELETE_FEELING';
export const ERROR_CREATE_POST = 'ERROR_CREATE_POST';
export const ERROR_POST_HAS_NO_DATA = 'ERROR_POST_HAS_NO_DATA';
export const ERROR_GET_EXCEPTED_POST_ID = 'ERROR_GET_EXCEPTED_POST_ID';
export const ERROR_GET_FRIEND_POST_ID = 'ERROR_GET_FRIEND_POST_ID';
export const ERROR_GET_STRANGER_POST = 'ERROR_GET_STRANGER_POST';
export const ERROR_GET_FRIEND_POST = 'ERROR_GET_FRIEND_POST';
export const ERROR_GET_POST_FOR_PAGINATION = 'ERROR_GET_POST_FOR_PAGINATION';
export const ERROR_GET_POST_PAGINATION = 'ERROR_GET_POST_PAGINATION';
export const ERROR_GET_STRANGER_POST_IDS = 'ERROR_GET_STRANGER_POST_IDS';

//SUCCESSFULLY
export const CREATE_FEELING_SUCCESSFULLY = 'CREATE_FEELING_SUCCESSFULLY';
export const UPDATE_FEELING_SUCCESSFULLY = 'UPDATE_FEELING_SUCCESSFULLY';
export const FIND_ALL_FEELING_SUCCESSFULLY = 'FIND_ALL_FEELING_SUCCESSFULLY';
export const DELETE_FEELING_SUCCESSFULLY = 'DELETE_FEELING_SUCCESSFULLY';
export const CREATE_POST_SUCCESSFULLY = 'CREATE_POST_SUCCESSFULLY';
export const GET_POST_PAGINATION_SUCCESSFULLY = 'GET_POST_PAGINATION_SUCCESSFULLY';
export const GET_POST_FOR_PAGINATION_SUCCESSFULLY = 'GET_POST_FOR_PAGINATION_SUCCESSFULLY';
