//ERROR
export const ERROR_CREATE_FEELING = 'ERROR_CREATE_FEELING';
export const ERROR_FEELING_IS_EXISTED = 'ERROR_FEELING_IS_EXISTED';
export const ERROR_UPDATE_FEELING = 'ERROR_UPDATE_FEELING';
export const ERROR_FIND_ALL_FEELING = 'ERROR_FIND_ALL_FEELING';
export const ERROR_DELETE_FEELING = 'ERROR_DELETE_FEELING';
export const ERROR_CREATE_POST = 'ERROR_CREATE_POST';
export const ERROR_POST_HAS_NO_DATA = 'ERROR_POST_HAS_NO_DATA';
export const ERROR_ADD_COMMENT_TO_POST = 'ERROR_ADD_COMMENT_TO_POST';
export const ERROR_GET_COMMENT_POST = 'ERROR_GET_COMMENT_POST';

//SUCCESSFULLY
export const CREATE_FEELING_SUCCESSFULLY = 'CREATE_FEELING_SUCCESSFULLY';
export const UPDATE_FEELING_SUCCESSFULLY = 'UPDATE_FEELING_SUCCESSFULLY';
export const FIND_ALL_FEELING_SUCCESSFULLY = 'FIND_ALL_FEELING_SUCCESSFULLY';
export const DELETE_FEELING_SUCCESSFULLY = 'DELETE_FEELING_SUCCESSFULLY';
export const CREATE_POST_SUCCESSFULLY = 'CREATE_POST_SUCCESSFULLY';
