//Error
export const ERROR_CREATE_SUBMESSAGE = 'ERROR_CREATE_SUBMESSAGE';
export const ERROR_SAW_SUBMESSAGE = 'ERROR_SAW_SUBMESSAGE';
//Success
export const CREATE_SUBMESSAGE_SUCCESS = 'CREATE_SUBMESSAGE_SUCCESS';
