//ERROR
export const ERROR_CREATE_USER = 'ERROR_CREATE_USER';
export const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
export const ERROR_PASSWORD_NOT_CORRECT = 'ERROR_PASSWORD_NOT_CORRECT';
export const ERROR_SIGN_IN_WITH_PHONE = 'ERROR_SIGN_IN_WITH_PHONE';
export const ERROR_VERIFY_USER = 'ERROR_VERIFY_USER';
export const ERROR_EMAIL_HAS_BEEN_USED = 'ERROR_EMAIL_HAS_BEEN_USED';
export const ERROR_PHONE_HAS_BEEN_USED = 'ERROR_PHONE_HAS_BEEN_USED';
export const ERROR_CHECK_USER_WITH_PHONE = 'ERROR_CHECK_USER_WITH_PHONE';
export const ERROR_CHECK_USER_WITH_GOOGLE = 'ERROR_CHECK_USER_WITH_GOOGLE';
export const EMAIL_NOT_MATCH_WITH_ID_TOKEN = 'EMAIL_NOT_MATCH_WITH_ID_TOKEN';

//SUCCESSFULLY
export const SIGN_IN_SUCCESSFULLY = 'SIGN_IN_SUCCESSFULLY';
export const SIGN_UP_SUCCESSFULLY = 'SIGN_UP_SUCCESSFULLY';
export const USER_EXISTED = 'USER_EXISTED';
export const USER_NOT_EXISTED = 'USER_NOT_EXISTED';
